spring.application.name=ScheduleMeetingBE

#jpa config
spring.datasource.url=jdbc:postgresql://${DB_HOST_POSTGRES}:5432/${DB_NAME_POSTGRES}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#swagger config
springdoc.swagger-ui.path=/api/v1/swagger-ui.html
springdoc.api-docs.path=/api/v1/api-docs
springdoc.swagger-ui.operationsSorter=alpha

#email config
spring.mail.port=587
spring.mail.host=smtp.gmail.com
spring.mail.username=${APP_EMAIL}
spring.mail.password=${APP_EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#redis config
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.password=${REDIS_PASS}
spring.data.redis.lettuce.pool.max-active=10
spring.data.redis.lettuce.pool.max-idle=5
spring.data.redis.lettuce.pool.min-idle=1

#flyway config
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1
spring.flyway.locations=classpath:db/migration
spring.flyway.placeholders.admin_username=${ADMIN_USERNAME}
spring.flyway.placeholders.admin_password_hash=${ADMIN_PASSWORD}
spring.flyway.placeholders.admin_email=${ADMIN_EMAIL}
