package com.example.schedulemeetingbe.constant.enums;

public enum EVENT_TYPE {
    USER_REGISTER,
    RESEND_EMAIL,
    RESET_PASSWORD,
    CREATE_USER,
    UPDATE_EMAIL,
    DELETE_AVATAR,
    BOOKING_CANCELLED_BY_MAINTENANCE,
    SEND_EMAIL_CONFIRM_PARTICIPATE
}
